services:
  gsuidcore:
    image: gsuidcore:latest
    container_name: gsuidcore
    restart: always
    environment:
      - TZ=Asia/Shanghai
    # ports:
    #   - 8765:8765
    volumes:
      - ./data:/app/data
      - ./gsuid_core:/app/gsuid_core
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./requirements.txt:/app/requirements.txt
      # stdin_open: true
    command: [ "sh", "-c", "poetry run core " ]
    networks:
      default:
        ipv4_address: 192.168.100.30

networks:
  default:
    external: true
    name: app
